name: Create docker image

on:
  push:
    tags:
      - '*'

jobs:
  add-tag:
    name: Create docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: abaplint/abaplint-docker
      - name: Build container
        run: |
          docker --version
          pwd
          docker build . --file Dockerfile --tag abaplint/abaplint:latest
      - name: Push container
        run: |
          docker images
          VERSION=$(docker run abaplint/abaplint:latest abaplint -v | tail -n 1)
          [ -n "${VERSION}" ] || echo "Cannot identify abaplint version"
          [ -n "${VERSION}" ] || exit 1
          echo "abaplint version:" $VERSION
          VERSION_2S=${VERSION%.*}
          VERSION_1S=${VERSION_2S%.*}
          echo "additional tags: $VERSION_2S, $VERSION_1S, latest"
          ./bin/push-containers.sh
